### DISCUSSION TITLE
Updating the stragegy and nothing changes?

### DISCUSSION THREAD

**Discussion by derekpurdy** [DigiLive/mushroom-strategy#111] [Q&A] [answered]
I'm making changes to the stragegy and nothing changes when I reload, do I need to force it to refresh some how?

**Comment by DigiLive** [comment]
Changes to what?
We need some more details in order to help you.

**Comment by derekpurdy** [comment]
I mean i updated from the example strategy and added tthe homeView hidden for greeting and its still there. Same with cover being "false"

```
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      light: true
      cover: false
    homeView:
      hidden:
        - greeting
views: []
```
