### DISCUSSION TITLE
Can't get it to work, following the Wiki

### DISCUSSION THREAD

**Discussion by insol-do** [DigiLive/mushroom-strategy#115] [Q&A] [answered]
Hello,

I followed the Wiki and have the error message below when adding the Raw Config code, please help.

"Unable to parse YAML: YAMLException: duplicated mapping key (266:1) 263 | entity: alarm_contr ... 264 | strategy: 265 | type: custom:mushroom-strategy 266 | views: [] -------^"

**Comment by DigiLive** [comment, marked as answer]
This means your yaml isn't valid.
Somewhere you duplicating an entry.

In the raw configuration editor the code should be at least:

```yaml
strategy:
  type: custom:mushroom-strategy
views: []
```

You can customize the strategy by setting options, e.g.

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      light:
        title: illumination
      switches:
        hidden: true
        icon: mdi:toggle-switch
    chips:
      weather_entity: weather.forecast_home
      climate_count: false
      cover_count: false
views: []
```

https://github.com/AalianKhan/mushroom-strategy/wiki/Full-Example
