### DISCUSSION TITLE
How can I change the settings (of the mushroom card) for an entire domain?

### DISCUSSION THREAD

**Discussion by wash02** [DigiLive/mushroom-strategy#137] [Q&A]
I am settings up a new smart home and so far the dashboard has been absolutely fantastic! However one small problem is the system automatically adds a button for oscilations for fans and tilt for blinds which are not supported on my devices. I want to remove this as it makes the interface confusing for other members of the house and clutters the interface.
The only way i've found to do this is by individually changing each entity under card_options. I have a lot of fans and blinds and so this would take quite a while to do manually and wouldnt scale for new devices, is there a way to do this for the whole domain (all fans/covers)? I can't find anything in the wiki.

Cheers in advance for any help.

**Comment by DigiLive** [comment]
Created #140 to follow-up this request.

**Comment by lukestein** [comment]
>… the system automatically adds a button for oscilations for fans and tilt for blinds which are not supported on my devices. I want to remove this as it makes the interface confusing for other members of the house and clutters the interface. The only way i've found to do this is by individually changing each entity under card_options.

Could you please help explain how you use `card_options` to do this (manually)? The only [card options listed in the docs](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#card-options) are `type` and `hidden` and I can't figure out how to apply further customization. I tried several variants of this and they didn't work, but it sounds like you have/had a way:

```
strategy:
  type: custom:mushroom-strategy
  card_options:
    fan.fan:
      type: custom:mushroom-fan-card
      show_percentage_control: false
      show_oscillate_control: false
views: []
```

**Reply by DigiLive** [reply]
The defaults for a fan entity are:
```
    type: "custom:mushroom-fan-card",
    icon: undefined,
    show_percentage_control: true,
    show_oscillate_control: true,
    icon_animation: true,
```

Any of these can be overridden or you can add [other fan properties](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/fan.md) to customize the card.
E.g.:
```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    card_options:
      fan.woonkamer_ventilator:
        show_percentage_control: false
        show_oscillate_control: false
views: []
```
