### DISCUSSION TITLE
How to backup?

### DISCUSSION THREAD

**Discussion by h1f1x** [DigiLive/mushroom-strategy#138] [Q&A] [answered]
I would like to know where the dashboard's config file is stored and how to back it up and restore it.
Like I want to do a lot more entries in the options part like:
```
strategy:
  type: custom:mushroom-strategy
  options:
    card_options: null
    areas:
      bad:
        icon: mdi:bathtub
views: []
```

But I don't want to lose it. 
Have searched in the homeassistant config folder, but could not find anything.
