### DISCUSSION TITLE
Adding icons/images to the Area icons in the Home page

### DISCUSSION THREAD

**Discussion by Knot83** [DigiLive/mushroom-strategy#143] [Q&A] [answered]
Hello, 
 Is there any way to change the Areas icons in the home page? I don’t like too much those blu generic icons.
The best would be to see a miniature of the picture I've for my Areas.
I've already tried to assign an icon in the HA settings of Areas but it doesn't work.
Thanks 

My config:

type: custom:mushroom-strategy
options: null
views: null
fans:
  hiddden: true

**Comment by DigiLive** [comment]
See the [Wiki](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#areas).

**Reply by Knot83** [reply]
> See the [Wiki](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#areas).

Unfortunatelly also following the wiki example I don’t see any new area, but I still see the default ones.
My new config:

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      family_room_id:
        name: Family Room
        icon: midi:sofa
        icon_color: green
views: []
```

What am I doing wrong?
Thanks
![4D4C69DE-046B-409D-BEC2-FBE5129B8EA3](https://github.com/AalianKhan/mushroom-strategy/assets/54513388/36d17fe0-b718-4321-82b9-8014571796eb)
