### DISCUSSION TITLE
Dashboard not updating after making changes

### DISCUSSION THREAD

**Discussion by BurningTheSky** [DigiLive/mushroom-strategy#148] [Q&A] [answered]
I have the dashboard installed and working in its base configuration but when I try to make changes to which areas are showing it make no difference and the all show. What have I missed? I imagine I've made a silly mistake

```
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      - name: Attic
        icon: mdi:home-roof
        icon_color: blue
      - name: Bathroom
        icon: mdi:shower
        icon_color: blue
views: []
```
