### DISCUSSION TITLE
Mushroom Cards Not Loading Properly. (Troubleshooting Guide?)

### DISCUSSION THREAD

**Discussion by youtopianycgmail** [DigiLive/mushroom-strategy#169] [Q&A]
I could not find one of these with a quick search. Might be useful to have a troubleshooting guide for this? Hopefully others will find this in the future.

I have installed Mushroom and followed the steps in https://github.com/AalianKhan/mushroom-strategy/discussions/90. 

I have redownloaded Mushroom.
Rebooted
Cleared Cache.
I can see the Resources
URL: /hacsfiles/mushroom-strategy/mushroom-strategy.js
Resourcetype: JavaScript-module.

Unsure how to check this part
Using YAML
The following code should be added to the lovelace section of configuration.yaml.

lovelace:
  resources:
    - url: /hacsfiles/mushroom-strategy/mushroom-strategy.js
      type: module
      
      Here is a list of the cards I have currently.
      
      
![image](https://github.com/user-attachments/assets/bc71ce2e-cd9f-4d41-8fc2-1074a9dc0707)

Any assistance with this would be greatly appreciated

**Comment by youtopianycgmail** [comment]
Installed the file explorer and added this to the end of my `configuration.yaml` file:

```yaml
lovelace:
  resources:
    - url: /hacsfiles/mushroom-strategy/mushroom-strategy.js
      type: module
```

My complete `configuration.yaml` file is listed below.

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
lovelace:
  resources:
    - url: /hacsfiles/mushroom-strategy/mushroom-strategy.js
      type: module
```
