### DISCUSSION TITLE
2.3.0 now does NOT show secondary information in areas

### DISCUSSION THREAD

**Discussion by dberrocal-git** [DigiLive/mushroom-strategy#198] [General]
```
      invernadero:
        order: 1
        icon: mdi:home-import-outline
        icon_color: blue
        secondary: >-
          🌡️{{ states('sensor.invernadero_ambiente_temperature') }}° 💧{{
          states('sensor.invernadero_ambiente_humidity') }}% 
          
```
          
  Secondary information is now not displayed. Do I have to change anything?

**Comment by DigiLive** [comment]
Not that I'm aware of.

The given information doesn't tell me much. Which card at which view are we discussing?

Please provide more code or maybe a screenshot.

**Reply by dberrocal-git** [reply]
Yes some screenshots, 
v2.3.0
![image](https://github.com/user-attachments/assets/4f9cb7be-b8b7-4855-aa6d-8e6256ced548)

v2.2.0
![image](https://github.com/user-attachments/assets/bbbc9239-b418-4370-a29a-f85bd7451bf3)

```
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      patio_delantero:
        order: 1
        icon: mdi:home-import-outline
        icon_color: blue
        type: default
        secondary: >-
          🌡️{{ states('sensor.invernadero_ambiente_temperature') }}° 💧{{
          states('sensor.invernadero_ambiente_humidity') }}% 
```
