### DISCUSSION TITLE
Lost previous Devices/Entities and New ones not all adding automatically

### DISCUSSION THREAD

**Discussion by gmogoody** [DigiLive/mushroom-strategy#221] [Q&A] [answered]
I have a weird scenario where the UniFi Network Integration appears to be running fine and if I go into settings entities everything is there and updated. Everything though no longer shows on any dashboard.  I also just installed a new integration with one of 30 entities automatically being added. 

I have cleared cache, tried other browsers, downloaded mushroom strategy again, created a completely new dashboard and force closed all apps but phone, iPAD and computer are all seeing this issue. Looked at the logs and there is nothing out of the ordinary. 

Any advice would be appreciated.

Installation methodHome Assistant OS
Core2025.5.2
Supervisor2025.05.1
Operating System15.2
MushroomStrategy 2.3.2

**Comment by DigiLive** [comment, marked as answer]
If those are `Configuration` or `Diagnostic` entities, these are hidden by default.
To include them you have to configure the regarding options:

```yaml
  options:
    domains:
      _: # Options for all domains
        hide_config_entities: false      # Show all configuration entities.
        hide_diagnostic_entities: false  # Show all diagnostic entities.
    card_options: # Options for entity cards.
      switch.my_diagnostic_entity:
        hidden: true                     # Hide this diagnostic entity anyway.
```

You can see the category of an entity at the device's view at `<hass-url>/config/device/<your-device-id>`?
Settings, Devices & Services, Devices, `<your-device>`.
