### DISCUSSION TITLE
v2.3.3

### DISCUSSION THREAD

**Discussion by DigiLive** [DigiLive/mushroom-strategy#230] [Announcements]
### 🚀 New Features

- Configuration Option: Set card count for horizontal stacks.  Resolves: #203
- Add Brazilian Portuguese language.  Resolves: #204
- Add Valve view.  Resolves: #223

```yaml
home_view:
  stack_count:
    _: 2
    persons: 3
    areas: [2,1] # [Strategy Card, HASS card]
domains:
  _:
    stack_count: 2
    light: 3
```

### 🐛 Bug Fixes
- Entities shown twice.  Resolves: #207
- Entities not shown.  Resolves: #227
- Area not found error.  Resolves: #206
- Unable to hide areas.  Resolves: #205
- Home view section split.  Resolves: #203

### 📚 Documentation
- [x] Add `stack_count` option to the Wiki.
- [x] Add `order` option for extra_views to the Wiki.
- [x] Add Valve to the documentation as supported domain.

> [!NOTE] 
> Our documentation is moving away from the Wiki to a brand-new site on GitHub Pages.
> Please update your bookmarks! You can find the complete and official documentation here:
> 👉 https://digilive.github.io/mushroom-strategy/
> The Wiki will not be updated anymore and will close soon.

<hr /><em>This discussion was created from the release <a href='https://github.com/DigiLive/mushroom-strategy/releases/tag/v2.3.3'>v2.3.3</a>.</em>
