### DISCUSSION TITLE
How do you edit a "person" card?

### DISCUSSION THREAD

**Discussion by thomashillyer** [DigiLive/mushroom-strategy#62] [Q&A] [answered]
This is the default look of a "user", I think it is either using a mushroom person card or a mushroom template card, but I don't know which or how to figure that out.

<img width="226" alt="image" src="https://github.com/AalianKhan/mushroom-strategy/assets/8906229/1f7a737d-0bbe-4f58-bee7-cba32f39083c">

I want to add information to the "secondary" field (if template card, or secondary_info if person card). 
I have tried adding details to card_options, extra_cards (which just adds a new card to the end of the page). I also tried doing card_options under quick_access_cards which does not seem to have any effect

```
strategy:
  type: custom:mushroom-strategy
  options:
    card_options:
      person.me:
        type: custom:mushroom-template-card
        secondary: Home
views: []
```
```
    quick_access_cards:
      - type: custom:mushroom-template-card
        entity: person.me
        secondary: Home
        card_options:
          person.me:
            icon: mdi:ab-testing
            secondary_info: some secondary info
```

How do i edit these people cards at the top of the page?
