### DISCUSSION TITLE
How to cast a mushroom-strategy dashboard?

### DISCUSSION THREAD

**Discussion by tmortensen** [DigiLive/mushroom-strategy#83] [Q&A]
I am trying to cast my dashboard but I get the following error. 

Error: Unable to find a view with path 0

I have tried to use the service call as well as using the cast button on the entity. 

I have tried adding a path: entry to my dashboard but no change to the error message.

**Comment by DigiLive** [comment]
You'll have to give more details...
From the info you gave now, I really don't know what you're trying to accomplish exactly and how you're trying it.

**Reply by dipseth** [reply]
I've had the same issue, the following service fails saying unable to find view lights.

Though I can indeed navigate to that view using the appropriate url
`<ha_root>/home_control/lights`

Top part of my config:

```
strategy:
  type: custom:mushroom-strategy
  name: home_control
  path: home_control
  options:
```

Service:
```
service: cast.show_lovelace_view
data:
  entity_id: media_player.kitchen_display_2
  dashboard_path: home_control
  view_path: lights
```

**Reply by DigiLive** [reply]
Thank you for your feedback.
Now I know what the OP actually was trying to do.

**Comment by DigiLive** [comment]
The strategy doesn't create a dashboard configuration, but configures a dashboard and views dynamically.

In your dashboard configuration there's probably something like:

```yaml
strategy:
  type: custom:mushroom-strategy
  options: {}
views: []
```

Given the following service call:

```yaml
service: cast.show_lovelace_view
data:
  entity_id: media_player.kitchen_display_2
  dashboard_path: home_control
  view_path: lights
```

I think the service expects to find the `lights` view defined in your dashboard configuration.
However, the `views` property is an empty array (`[]`) and therefor the view isn't found and can't be cast.

Unfortunately, the way we configure the views now, results in being unable to cast the dashboard when using our strategy at the moment.
