### ISSUE TITLE
Merging of areas defined in strategy-options and other areas of Home Assistant

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/mushroom-strategy#11]
**Is your feature request related to a problem? Please describe.**
Currently creating area cards for areas, defined in strategy-options, has precedence over creating cards for areas defined in Home Assistant. In other words, only cards of areas in the config are created or only cards of Home Assistant areas are created.

**Describe the solution you'd like**
I'd like to propose the following:
- Create cards for Home Assistant areas with a default config.
- Entries in the strategy-options with the same `area_id` (instead of `name`), override the default config.
- Explicit exclusion of an area by a property in strategy-options.

This way we get a merge of default and custom cards of Home Assistant areas.
Areas defined in strategy-options must exist in Home Assistant anyway.

E.g.
```yaml
  options:
    areas:
      - family_room:
          name: Family Room
          icon: mdi:sofa
          icon_color: green
      - bedroom:
          hidden: true
          name: Fun Place
          icon: mdi:bed-outline
          icon_color: red
```

**Describe alternatives you've considered**
Define configurations in the strategy-options for all areas, just to customize a few of them.
This means defining the same configuration for a lot of areas which actually where meant to be untouched.

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/7613487/232015791-6b8152c5-6c29-407c-b12e-601d473459ba.png)
