### ISSUE TITLE
Allow showControls for all `_` Domains

### ISSUE THREAD

**Issue by pavolholes** [DigiLive/mushroom-strategy#126]
**Is your feature request related to a problem? Please describe.**
I would like to disable controls for all domains (lights and switches and covers etc.) so they can't be turned on or turned off unintentionally.

**Describe the solution you'd like**
```
strategy:
  type: custom:mushroom-strategy
  options:
    domains:
      _:
        showControls: false
```

**Describe alternatives you've considered**
Below is working
```
strategy:
  type: custom:mushroom-strategy
  options:
    domains:
      light:
        showControls: false
      switch:
        showControls: false
      cover:
        showControls: false
      vacuum:
        showControls: false
```

Edit 07-02-2024: Issue below is fixed.
<del>
**Additional context**
There is a typo mistake in the Domain [example](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#example-5) where the `light:` is written as `lights.`
</del>
