### ISSUE TITLE
Wrong "turned on" entities count for domains/views/chips

### ISSUE THREAD

**Issue by maslyankov** [DigiLive/mushroom-strategy#129]
**Describe the bug**
The entities that are on for domain/view and also in chips have some miscalculation because they count the unavailable devices/entities as "ON" and are included in the count of "X climates on" for example and the according chip card.

**Versions**
* Mushroom-Strategy: v2.1.0
* HACS: latest
* Mushroom: latest
* Home Assistant: 2024.2.2

**To Reproduce**

1. Have a unavailable entity
2. Go to 'Home' or device view/domain
3. Check count
4. See error where entities "turned on" count contains ("turned on" + "unavailable")

**Expected behavior**
Unavailable entities should not be counted as ON.

**Screenshots**

**Additional context**

**Comment by DigiLive** [comment]
Actually it's not an `on` status for all domains.
See the overview below:

Fan: `is on`
Switch: `is on`
Light: `is on`
Climate: `not off`
Cover: `is open`

Since `unavailable` is a member of the `not off` status, it's counted indeed.
I also think it's better to remove `unavailable` entities from the climate count.

**Comment by w531t4** [comment]
This issue can be re-created by adding the following config into homeassistant, restarting homeassistant (not reload, but full restart), and then in developer tools, set the state of climate.garage_climate to unavailable. 

```
climate:
  - platform: generic_thermostat
    unique_id: 2f9c2e62-6dc7-43f2-95ca-9d2191bbe6d9
    name: Garage Climate
    heater: switch.temp_heater
    target_sensor: sensor.garage_test_temperature

switch:
  - platform: template
    switches:
      temp_heater:
        friendly_name: Garage_Test_Heater
        unique_id: 13316cfa-5a3d-4866-aefa-0d6b48f6b29f
        turn_on:
        turn_off:

template:
  - sensor:
      - name: Garage_Test_Temperature
        unique_id: 5fda973c-5f5c-496d-86f6-38196411f9ce
        state: "0.1"
```

Unavailable light entities don't appear to affect the totals.
