### ISSUE TITLE
Support for more entity domains

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/mushroom-strategy#14]
Currently the following domains are supported as a view (top bar):
* light
* fan
* cover
* switch
* climate
* cameras

Entities of other domains will not be included on the dashboard, **unless** they're assigned to an area.
These can only be found in the sub-view of an area (Area card on view `Home`).

So, entities (of other domains as listed above) which **aren't** assigned to an area, aren't included at all and nowhere to be found on the dashboard.

**Describe the solution you'd like**
A new view named `Other` at the top bar which includes all entities of other domains as listed above.
E.g.
![afbeelding](https://user-images.githubusercontent.com/7613487/232791761-1016005c-3239-47e5-a7ef-ae36c0e1a243.png)

In addition/As alternative, set which domains to include as a configuration option.
(Where unconfigured results in default domains, like the current ones.)

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      - light
      - switch
      - domainByChoice
      - ...
views: []
```

instead of:

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      lights: true
      switches: true
      covers: false
      cameras: true
      thermostats: false
views: []
