### ISSUE TITLE
no cover added automatically

### ISSUE THREAD

**Issue by jluc2808** [DigiLive/mushroom-strategy#19]
**Describe the bug**
after an clean install of the plugin and a simple yaml config, i got no cover in the cover section.  Otherwise light, thermostat, Rooms are OK. 

my config: 
```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      lights: true
      fans: false
      switches: false
      covers: true
      cameras: true
      thermostats: true
views: []
```

and i have several cover otherwise, by example : 
`entity: cover.extension_14_1_fgwr_111_bso1_61`

**Expected behavior**
how could i solve ? 

**Additional context**
my installation: 
HAOS on Rpi4 (armv7) 
last HACS 
integration with additional module of HACS 
every pre-requisit installed
