### ISSUE TITLE
Unable to hide named areas

### ISSUE THREAD

**Issue by jstys** [DigiLive/mushroom-strategy#205]
### What happened?

Named areas set to `hidden: true` are no longer hidden in the home view.  The "Undisclosed" area does hide properly.

### Steps to reproduce

```yaml
hallway:
        name: Hallway
        icon: mdi:door
        order: 11
        hidden: true
```

### Versions

- Mushroom Dashboard: 2.3.1
- Lovelace Mushroom: 4.4.0
- Home Assistant: 2025.4.4

### Environment

Web Browser (specify name and version)

### Environment and Version

Firefox 137.0.2

### Expected Behavior

Area should be hidden as it was in the previous release

### Actual Behavior

Area is still visible

### Error Logs (if applicable)

```plain text

```

### Guidelines

- [x] I have read and agree to the guidelines.
