### ISSUE TITLE
"Area not found" error thrown when using HaAreaCard for area card type

### ISSUE THREAD

**Issue by zbulb** [DigiLive/mushroom-strategy#206]
### What happened?

When using area card type = HaAreaCard, a "Area not found" error is thrown; no error thrown when using area card type = default

### Steps to reproduce

Configuration used as follow

```
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      _:
        type: HaAreaCard
        aspect_ratio: 25%
views: []
```

![Image](https://github.com/user-attachments/assets/17d23122-3f84-40bd-9d51-98d4c847c8cb)

### Versions

- Mushroom Dashboard: 2.3.1
- Lovelace Mushroom: 4.4.0
- Home Assistant: 2025.5.0

### Environment

Web Browser (specify name and version)

### Environment and Version

Microsoft Edge (136.0.3240.64)

### Expected Behavior

The "Area not found" error should not be thrown

### Actual Behavior

"Area not found" error is thrown

### Error Logs (if applicable)

```plain text

```

### Guidelines

- [x] I have read and agree to the guidelines.
