### ISSUE TITLE
Everything works like a charm, except my security cameras.

### ISSUE THREAD

**Issue by messinabr** [DigiLive/mushroom-strategy#28]
Everything works like a charm, except my security cameras.

When I go to the cameras, it shows my 3 cameras but with this error:
Cant get URL for camera.namefomycamera

![image](https://github.com/AalianKhan/mushroom-strategy/assets/114037719/d86317d9-dc11-467d-9e2e-dc1bb514438c)

Any suggestions of what might be causing the problem:?

**Comment by DigiLive** [comment]
This library uses cards from [WebRTC Camera](https://github.com/AlexxIT/WebRTC) which in turn makes use of [go2rtc](https://github.com/AlexxIT/go2rtc).

You should report your issue at https://github.com/AlexxIT/go2rtc/issues for support.
I have this issue myself with NEST cameras, which apparently aren't supported (yet).

Alternatively, you can override the type of the card in the dashboard configuration to a type which does work.
E.g.
```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    entity_config:
      - entity: camera.sala
        type: picture-entity
```

Please keep me informed.

**Comment by AalianKhan** [comment]
@DigiLive, do you think it is somehow possible to retrieve an error if the WebRTC card worked or not and react accordingly?

Also, since this issue has popped up a few times, I think should we consider using something like the picture entity card which will work _every time_? If someone wants to use WebRTC, they can use the `entity_config`.

**Comment by DigiLive** [comment]
> @DigiLive, do you think it is somehow possible to retrieve an error if the WebRTC card worked or not and react accordingly?

I don't think so. Our code runs before the code of webRTC.

> Also, since this issue has popped up a few times, I think should we consider using something like the picture entity card which will work _every time_? If someone wants to use WebRTC, they can use the `entity_config`.

I prefer using the the default hass card (picture entity) as well.

- Integrates with hass the best.
- Most likely updated by the hass team in relation to bugs, enhancements and compatibility.
- Less extra required plugins (WebRTC and got2rtc).

Also, the picture entity card has its limitations.
E.g. An incompatibility between Firefox and Nest webRTC, it will also give an error.
Works fine in other browsers, though.

**Comment by cmerkle** [comment]
I am having the same problem I have several Nest cameras and cannot get them to show up in the dashboard. I have added the following to my configuration per the above recommendation but it doesn't seem to change anything:

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    entity_config:
      - entity: camera.living_room_camera
        type: picture-entity
      - entity: camera.front_yard_camera
        type: picture-entity
      - entity: camera.kitchen_camera
        type: picture-entity
      - entity: camera.backyard_camera
        type: picture-entity
      - entity: camera.garage_camera
        type: picture-entity
      - entity: camera.driveway_camera
        type: picture-entity
      - entity: camera.raspberrypi_logitech_c920
        type: picture-entity
      - entity: camera.raspberrypi_thumbnail
        type: picture-entity
views: []
```

![image](https://github.com/AalianKhan/mushroom-strategy/assets/33108196/77ec4c58-e790-4c87-8087-6a1dd20932c3)
