### ISSUE TITLE
Which file to edit to change icons here?

### ISSUE THREAD

**Issue by kmanan** [DigiLive/mushroom-strategy#30]
![IMG_6333](https://github.com/AalianKhan/mushroom-strategy/assets/17659155/791f42b6-b6a0-444e-abe5-94e902da89c1)

n00b question: which specific file do I edit to change icons here?

**Comment by DigiLive** [comment]
This is only possible since version [1.0.0-apha.1](https://github.com/AalianKhan/mushroom-strategy/releases/tag/1.0.0-alpha.1).

In the UI of the dashboard, click the 3 dots in the top right corner to edit the dashboard configuration.

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      family_room_id:
        icon: mdi:sofa
views: []
```

Make sure `family_room_id` matches the id of your hass area.

**Comment by kmanan** [comment]
Interesting. It seems like i'm doing something basic wrong. I have updated the file to this but keep getting this error

```yaml
 strategy:
   type: custom:mushroom-strategy
   options:
     areas:
       living_room_id:
         name: Living Room
         icon: mdi:sofa
 views: []
```

![image](https://github.com/AalianKhan/mushroom-strategy/assets/17659155/95cf6393-e5eb-48e7-aa36-140871f7c7bc)

**Comment by DigiLive** [comment]
Please place your yaml configuration inside a code block when posting here.
You can use the `< >` button for it.
Without a proper format, I can't check for syntax errors in you configuration.

E.g.
```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      living_room_id:
        name: Living Room
        icon: mdi:sofa
views: []
```
