### ISSUE TITLE
Can't change area icon

### ISSUE THREAD

**Issue by cmerkle** [DigiLive/mushroom-strategy#37]
I am trying to change the icons for the different areas in the mushroom strategy dashboard, however after editing the config per the README I am getting and error that states:

"""
Error loading the dashboard strategy:

TypeError: strategyOptions.areas is not iterable
"""

My configuration is below:

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      living_room_id:
        name: Living Room
        icon: mdi:sofa
        icon_color: green
    entity_config:
      - entity: camera.living_room_camera
        type: picture-entity
      - entity: camera.front_yard_camera
        type: picture-entity
      - entity: camera.kitchen_camera
        type: picture-entity
      - entity: camera.backyard_camera
        type: picture-entity
      - entity: camera.garage_camera
        type: picture-entity
      - entity: camera.driveway_camera
        type: picture-entity
      - entity: camera.raspberrypi_logitech_c920
        type: picture-entity
      - entity: camera.raspberrypi_thumbnail
        type: picture-entity
views: []
```

![image](https://github.com/AalianKhan/mushroom-strategy/assets/33108196/889ed5dd-7068-4714-b138-0e9e737296d9)
