### ISSUE TITLE
Improve Areas on Home view

### ISSUE THREAD

**Issue by punxaphil** [DigiLive/mushroom-strategy#49]
What an amazing dashboard strategy you have created. Thanks! 👏 Great work and finally I can get rid of Dwains Dashboard (it was great for a while, but has been very buggy lately for me).

Two things:
1.  I'd like to be able to configure the title for "Areas" in the Home view (much like I can set the title for domains)
2. "Areas" title looks misplaced to me. It is in the left column, while all areas are in the right column. Please see screenshot:
<img width="1011" alt="image" src="https://github.com/AalianKhan/mushroom-strategy/assets/26582898/c778d5fa-4d31-4a98-bcb0-5240faa4cda0">

**Comment by AalianKhan** [comment]
What would you like to change areas to?

**Comment by punxaphil** [comment]
I'd like to translate it to Swedish. Something like this:
```
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
       title: Områden
```

**Comment by punxaphil** [comment]
Much like I've done with the domains:
```
strategy:
  type: custom:mushroom-strategy
  options:
    domains:
      light:
        title: Lampor
      media_player:
        title: Spelare
      cover:
        title: Mörkläggning
      switch:
        hidden: true
      binary_sensor:
        hidden: true
      sensor:
        title: Sensorer
      climate:
        title: AC
      default:
        title: Övrigt
```
