### ISSUE TITLE
Strategy stopped working

### ISSUE THREAD

**Issue by brianveno827** [DigiLive/mushroom-strategy#64]
strategy stopped working when I installed the new version

Error:
Error loading the dashboard strategy:

Error: Timeout waiting for strategy element ll-strategy-mushroom-strategy to be registered

Raw Data:
```yaml
strategy:
  type: custom:mushroom-strategy
views: []
```
