### ISSUE TITLE
How to use custom entities of configuration.yaml?

### ISSUE THREAD

**Issue by superabbite1** [DigiLive/mushroom-strategy#67]
The custom entities in configuration.yaml do not have area information. How can these entities be used?

**Comment by DigiLive** [comment]
Entities need a `unique_id` to be listed in HA entity-register and to assign them to an area.

Did you read the [Adding devices to areas](https://github.com/AalianKhan/mushroom-strategy/blob/main/README.md#adding-devices-to-areas) section in the readme?

Maybe it's a solution for your situation!?

**Comment by AalianKhan** [comment]
Unfortunately, some entities created via the `configuration.yaml` file are not able to have a `unique_id`.
You can use the [`extra_cards`](https://github.com/AalianKhan/mushroom-strategy#area-object) option for areas to add a card on the top of the view.

For example
```YAML
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      family_room_id:
        name: Family Room
        icon: mdi:television
        icon_color: green
        order: 1
        extra_cards:
          - type: custom:mushroom-entity-card
            entity: cover.curtain
```

**Comment by superabbite1** [comment]
For example, I have customized the following code entities in configuration.yaml. How should I configure the area so that mushroom can recognize it?
```yaml
cover:
  - platform: template
    covers:
      custom_cover:
        device_class: gate
        friendly_name: "curtain test"
        position_template: "{{ states('input_number.cover_position') }}"
        open_cover:
          service: select.select_option
          data:
            entity_id: select.remote_ir_1706309535964229632
            option: open
        close_cover:
          service: select.select_option
          data:
            entity_id: select.remote_ir_1706309535964229632
            option: close
        stop_cover:
          service: select.select_option
          data:
            entity_id: select.remote_ir_1706309535964229632
            option: stop
```

**Comment by AalianKhan** [comment]
You would enter a random [`unqiue_id`](https://www.home-assistant.io/integrations/cover.template/#unique_id)
```YAML
cover:
  - platform: template
    covers:
      custom_cover:
        device_class: gate
        friendly_name: "curtain test"
        unique_id: Q1NUj4D3mPVI822TKQXlrcgL
        ...
```
