### ISSUE TITLE
Greeting is not hidden when disabled in homeView options

### ISSUE THREAD

**Issue by gottsman** [DigiLive/mushroom-strategy#82]
**Describe the bug**  
I have tried to disable the greeting message at the top of the interface. Adding the hidden option seems to have no affect on visibility.

**Versions**  
* Mushroom-Strategy: 1.0.1
* HACS: 1.33
* Mushroom: 3.2.2
* Home Assistant: 2023.11.0

**To Reproduce**  
Here is my current config:
```
strategy:
  type: custom:mushroom-strategy
  options:
    homeView:
      hidden:
        - Greeting
    chips:
      climate_count: false
      cover_count: false
views: []
```

**Expected behavior**  
Expected to see a simpler interface without the greeting message

**Screenshots**  
![minimalist greeting](https://github.com/AalianKhan/mushroom-strategy/assets/6173136/01860f7c-e725-4aeb-b9db-e4c5623384c2)

**Additional context**

**Comment by DigiLive** [comment]
The entries are case sensitive.
Please try them without any capitals.

**Comment by gottsman** [comment]
I tried the example from the README.md file located at Aalian's repo:
[https://github.com/AalianKhan/mushroom-strategy#home-view-options](https://github.com/AalianKhan/mushroom-strategy#home-view-options)

Even this example is not working for me - direct copy/paste
```
strategy:
  type: custom:mushroom-strategy
  options:
    homeView:
      hidden:
        - greeting
        - areasTitle
views: []
```

**Comment by DigiLive** [comment]
Ok, thanks.
I will look into it.

**Comment by DigiLive** [comment]
Version 1.0.1 doesn't include this feature.

It seems HACS shows the readme of the latest commit instead of the released one.

If you want to use this feature, you'll have to copy the latest `.js` file in the `dist` directory to your Home Assistant instance manually.

(Remember to remove the compressed file and to refresh your client's cache)

I've reported the readme issue to HACS [#3330](https://github.com/hacs/integration/issues/3330)

**Comment by DigiLive** [comment]
I've reported the problem of the readme to HACS.
Also, a new release which includes this and some other features is coming soon.

In the meanwhile you could choose to download `main` at the HACS integration of your Home Assistant instance. (See https://hacs.xyz/docs/faq/select_version/)

![afbeelding](https://github.com/AalianKhan/mushroom-strategy/assets/7613487/0610ad2f-b441-41d8-be7a-a894e56ee4f6)

@gottsman Please let me know if downloading the `main` version works out for you.

**Comment by gottsman** [comment]
Works as expected. The greeting is now hidden properly. Thanks for your quick response.

**Comment by gottsman** [comment]
Seems like I have broken something. After trying multiple installs/reinstalls, browsers and cache clearing, I am no longer able to get the example to work. Using the code "main" instead of 1.01.

Using the same example from above:
```
strategy:
  type: custom:mushroom-strategy
  options:
    homeView:
      hidden:
        - greeting
        - areasTitle
views: []
```

**Comment by DigiLive** [comment]
It seems like HACS doesn't always download the requested version.
You can verify the downloaded version in the upper-left corner:
![afbeelding](https://github.com/AalianKhan/mushroom-strategy/assets/7613487/6858d0ce-9ea5-42b1-8b09-82ea0e9f812f)

You can keep trying to re-download or manually copy the attached file to `/homeassistant/www/community/mushroom-strategy` of your HASS instance.
Also extract its contents to the same directory and clear the cache.

[mushroom-strategy.js.gz](https://github.com/AalianKhan/mushroom-strategy/files/13367754/mushroom-strategy.js.gz) (6,547 bytes)

I've reported the issue to HACS [#3345](https://github.com/hacs/integration/issues/3345)

**Comment by gottsman** [comment]
Thanks. Its fixed again with the attached file. I will follow the HACS issue report.

**Comment by derekpurdy** [comment]
I assume this should be working with 2.0 that was just released? I still cannot get the greeting to hide.

```
strategy:
  type: custom:mushroom-strategy
  options:
    homeView:
      hidden:
        - greeting
views: []
```

**Comment by clowgg** [comment]
> I assume this should be working with 2.0 that was just released? I still cannot get the greeting to hide.
> 
> ```
> strategy:
>   type: custom:mushroom-strategy
>   options:
>     homeView:
>       hidden:
>         - greeting
> views: []
> ```

Same here. Greeting doesn't hide, and the areas customisations don't work either.
(partial yaml file shown)
```
strategy:
  type: custom:mushroom-strategy
  options:
    areas:
      front_of_home_id:
        name: Front of Home
        icon: mdi:home
        icon_color: green
        order: 1
      entrance_id:
        name: Entrance
        icon: mdi:home-lightbulb
        icon_color: lime
        order: 2
```

**Comment by DigiLive** [comment]
The Wiki didn't include the changes of the home view option during development.

It should be `home_view` instead of `homeView`:

```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    home_view:
      hidden:
        - greeting
views: []
```
